package com.sutec.mobile.server.seed

import com.sutec.mobile.data.model.Category
import com.sutec.mobile.data.model.Product
import com.sutec.mobile.data.model.ProductTag
import com.sutec.mobile.data.model.Review

// カタログのシード。client の MockCatalog と同一データ(画像は相対パス images/<id>-<n>.jpg)。
// id は cart/wishlist/order の参照キーのため変更時は影響範囲を確認する。
object CatalogSeed {

    // 相対パス。server が /images 静的配信し、client が API ベースURLで解決する。
    private fun images(id: String, count: Int): List<String> =
        (1..count).map { "images/$id-$it.jpg" }

    val categories: List<Category> = listOf(
        Category("electronics", "家電・電化製品", "Electronics", "📱"),
        Category("fashion", "ファッション", "Fashion", "👕"),
        Category("home", "ホーム・キッチン", "Home & Kitchen", "🏠"),
        Category("beauty", "ビューティー", "Beauty", "💄"),
        Category("books", "本", "Books", "📚"),
        Category("sports", "スポーツ・アウトドア", "Sports & Outdoors", "⚽"),
        Category("grocery", "食品・飲料", "Grocery", "🛒"),
        Category("toys", "おもちゃ", "Toys", "🧸"),
    )

    val products: List<Product> = listOf(
        // ===== electronics =====
        Product(
            id = "electronics_1",
            nameJa = "ワイヤレスイヤホン Pro", nameEn = "Wireless Earbuds Pro",
            brandJa = "サウンドウェーブ", brandEn = "SoundWave",
            descriptionJa = "高音質なノイズキャンセリング機能を搭載したワイヤレスイヤホンです。最大24時間の連続再生が可能で、防水性能も備えています。",
            descriptionEn = "Wireless earbuds with high-quality active noise cancellation. Up to 24 hours of battery life and water resistance for everyday use.",
            priceYen = 8900, listPriceYen = 12000, categoryId = "electronics",
            imageUrls = images("electronics_1", 4), rating = 4.5, reviewCount = 1200,
            tags = listOf(ProductTag.BESTSELLER, ProductTag.PRIME),
        ),
        Product(
            id = "electronics_2",
            nameJa = "4Kスマートテレビ 50インチ", nameEn = "4K Smart TV 50-inch",
            brandJa = "テックノヴァ", brandEn = "TechNova",
            descriptionJa = "鮮やかな4K解像度と豊富な動画配信アプリに対応したスマートテレビです。薄型デザインでどんな部屋にもなじみます。",
            descriptionEn = "A vivid 4K smart TV with built-in access to popular streaming apps. Its slim design fits seamlessly into any living space.",
            priceYen = 65000, categoryId = "electronics",
            imageUrls = images("electronics_2", 3), rating = 4.3, reviewCount = 340,
            tags = listOf(ProductTag.PRIME),
        ),
        Product(
            id = "electronics_3",
            nameJa = "メカニカルキーボード 日本語配列", nameEn = "Mechanical Keyboard JIS Layout",
            brandJa = "キーフォージ", brandEn = "KeyForge",
            descriptionJa = "タクタイル感のある打鍵感が特徴のメカニカルキーボードです。バックライト付きで長時間の作業も快適です。",
            descriptionEn = "A mechanical keyboard with satisfying tactile feedback. Backlit keys make long working sessions comfortable even in dim light.",
            priceYen = 12500, listPriceYen = 15000, categoryId = "electronics",
            imageUrls = images("electronics_3", 3), rating = 4.6, reviewCount = 560,
            tags = listOf(ProductTag.SALE),
        ),
        Product(
            id = "electronics_4",
            nameJa = "モバイルバッテリー 10000mAh", nameEn = "Portable Charger 10000mAh",
            brandJa = "パワーセル", brandEn = "PowerCell",
            descriptionJa = "コンパクトながら大容量の10000mAhモバイルバッテリー。スマートフォンを約3回フル充電できます。",
            descriptionEn = "A compact yet high-capacity 10000mAh power bank that can fully charge a smartphone about three times.",
            priceYen = 2480, categoryId = "electronics",
            imageUrls = images("electronics_4", 4), rating = 4.2, reviewCount = 2300,
            tags = listOf(ProductTag.BESTSELLER, ProductTag.PRIME),
        ),
        Product(
            id = "electronics_5",
            nameJa = "ロボット掃除機 スマートナビ", nameEn = "Robot Vacuum Smart Nav",
            brandJa = "クリーンボット", brandEn = "CleanBot",
            descriptionJa = "間取りを学習して効率的に清掃するロボット掃除機です。アプリ連携でスケジュール設定も簡単に行えます。",
            descriptionEn = "A robot vacuum that learns your floor plan for efficient cleaning. Schedule cleanings easily through the companion app.",
            priceYen = 45000, listPriceYen = 58000, categoryId = "electronics",
            imageUrls = images("electronics_5", 4), rating = 4.4, reviewCount = 890,
            tags = listOf(ProductTag.SALE, ProductTag.NEW),
        ),
        Product(
            id = "electronics_6",
            nameJa = "13インチ ウルトラブック", nameEn = "13-inch Ultrabook Laptop",
            brandJa = "ノヴァブック", brandEn = "NovaBook",
            descriptionJa = "軽量ボディに高性能プロセッサを搭載した13インチノートパソコンです。1kg未満で持ち運びやすく、バッテリーは最大18時間持続します。",
            descriptionEn = "A 13-inch laptop packing a high-performance processor into a featherweight body. At under 1kg, it's easy to carry and lasts up to 18 hours on a charge.",
            priceYen = 119800, listPriceYen = 138000, categoryId = "electronics",
            imageUrls = images("electronics_6", 3), rating = 4.6, reviewCount = 145,
            tags = listOf(ProductTag.PRIME),
        ),
        Product(
            id = "electronics_7",
            nameJa = "USB-C 充電ケーブル 2m", nameEn = "USB-C Charging Cable 2m",
            brandJa = "コネクトプロ", brandEn = "ConnectPro",
            descriptionJa = "耐久性の高い編み込みタイプのUSB-C充電ケーブルです。急速充電に対応し2mの長さで自由な使い方ができます。",
            descriptionEn = "A durable braided USB-C charging cable supporting fast charging. The 2-meter length gives flexibility in how you use it.",
            priceYen = 500, categoryId = "electronics",
            imageUrls = images("electronics_7", 3), rating = 4.0, reviewCount = 640,
        ),

        // ===== fashion =====
        Product(
            id = "fashion_1",
            nameJa = "メンズ デニムジャケット", nameEn = "Men's Denim Jacket",
            brandJa = "アーバンスレッド", brandEn = "Urban Thread",
            descriptionJa = "定番のデニムジャケットはカジュアルなコーディネートに最適です。丈夫な生地で長く着用できます。",
            descriptionEn = "A timeless denim jacket that pairs well with any casual outfit. Made from sturdy fabric built to last for years.",
            priceYen = 7900, categoryId = "fashion",
            imageUrls = images("fashion_1", 3), rating = 4.1, reviewCount = 220,
        ),
        Product(
            id = "fashion_2",
            nameJa = "サマーワンピース フローラル柄", nameEn = "Floral Summer Dress",
            brandJa = "サニーブルーム", brandEn = "Sunny Bloom",
            descriptionJa = "軽やかな素材で作られたフローラル柄のワンピースです。デイリーからお出かけまで幅広く活躍します。",
            descriptionEn = "A lightweight floral dress perfect for both everyday wear and special outings. Breathable fabric keeps you comfortable in warm weather.",
            priceYen = 5400, listPriceYen = 7200, categoryId = "fashion",
            imageUrls = images("fashion_2", 4), rating = 4.3, reviewCount = 410,
            tags = listOf(ProductTag.SALE, ProductTag.NEW),
        ),
        Product(
            id = "fashion_3",
            nameJa = "レザースニーカー", nameEn = "Leather Sneakers",
            brandJa = "ステップイーズ", brandEn = "StepEase",
            descriptionJa = "上質な本革を使用したシンプルなデザインのスニーカーです。クッション性の高いインソールで一日中快適に過ごせます。",
            descriptionEn = "Genuine leather sneakers with a clean, minimal design. The cushioned insole keeps your feet comfortable all day long.",
            priceYen = 9800, categoryId = "fashion",
            imageUrls = images("fashion_3", 4), rating = 4.5, reviewCount = 780,
            tags = listOf(ProductTag.BESTSELLER),
        ),
        Product(
            id = "fashion_4",
            nameJa = "ウールマフラー", nameEn = "Wool Scarf",
            brandJa = "ウールクラフト", brandEn = "WoolCraft",
            descriptionJa = "上質なウール100%のマフラーです。柔らかな肌触りで冬の寒さから首元を優しく守ります。",
            descriptionEn = "A soft 100% wool scarf that gently protects your neck from the winter chill. The gentle texture feels great against the skin.",
            priceYen = 3200, categoryId = "fashion",
            imageUrls = images("fashion_4", 3), rating = 4.0, reviewCount = 95,
        ),
        Product(
            id = "fashion_5",
            nameJa = "ミニマルデザイン腕時計", nameEn = "Minimalist Wrist Watch",
            brandJa = "タイムミニマル", brandEn = "TimeMinimal",
            descriptionJa = "無駄を削ぎ落としたシンプルなデザインの腕時計です。ビジネスからカジュアルまで幅広いシーンで活躍します。",
            descriptionEn = "A wristwatch stripped down to its essentials for a clean, minimal look. Versatile enough for both business and casual occasions.",
            priceYen = 18000, listPriceYen = 24000, categoryId = "fashion",
            imageUrls = images("fashion_5", 4), rating = 4.7, reviewCount = 610,
            tags = listOf(ProductTag.SALE, ProductTag.PRIME),
        ),

        // ===== home =====
        Product(
            id = "home_1",
            nameJa = "セラミック包丁3本セット", nameEn = "Ceramic Knife Set of 3",
            brandJa = "シェフエッジ", brandEn = "ChefEdge",
            descriptionJa = "錆びにくく切れ味が長持ちするセラミック包丁のセットです。軽量で扱いやすく毎日の料理を快適にします。",
            descriptionEn = "A set of three ceramic knives that resist rust and hold their edge for a long time. Lightweight and easy to handle for everyday cooking.",
            priceYen = 4500, categoryId = "home",
            imageUrls = images("home_1", 3), rating = 4.2, reviewCount = 150,
        ),
        Product(
            id = "home_2",
            nameJa = "低反発枕 ネックフィット", nameEn = "Memory Foam Pillow Neck Fit",
            brandJa = "クラウドレスト", brandEn = "CloudRest",
            descriptionJa = "首と頭をやさしく支える低反発枕です。通気性の良いカバー付きで一晩中快適な眠りをサポートします。",
            descriptionEn = "A memory foam pillow that gently cradles your neck and head. The breathable cover helps support comfortable sleep all night.",
            priceYen = 3980, categoryId = "home",
            imageUrls = images("home_2", 4), rating = 4.4, reviewCount = 980,
            tags = listOf(ProductTag.BESTSELLER),
        ),
        Product(
            id = "home_3",
            nameJa = "フッ素加工フライパン 26cm", nameEn = "Non-stick Frying Pan 26cm",
            brandJa = "パンクラフト", brandEn = "PanCraft",
            descriptionJa = "焦げ付きにくいフッ素加工を施したフライパンです。少ない油でヘルシーな調理ができます。",
            descriptionEn = "A frying pan with a non-stick coating that resists burning. Cook healthier meals using less oil.",
            priceYen = 2800, listPriceYen = 3600, categoryId = "home",
            imageUrls = images("home_3", 3), rating = 4.1, reviewCount = 340,
            tags = listOf(ProductTag.SALE),
        ),
        Product(
            id = "home_4",
            nameJa = "LEDデスクライト 調光式", nameEn = "LED Desk Lamp Dimmable",
            brandJa = "グロウデスク", brandEn = "GlowDesk",
            descriptionJa = "明るさを自由に調整できるLEDデスクライトです。目に優しい光で読書や作業の集中をサポートします。",
            descriptionEn = "An LED desk lamp with adjustable brightness. The eye-friendly light helps you focus during reading or work.",
            priceYen = 3500, categoryId = "home",
            imageUrls = images("home_4", 3), rating = 4.3, reviewCount = 210,
            tags = listOf(ProductTag.NEW, ProductTag.PRIME),
        ),
        Product(
            id = "home_5",
            nameJa = "空気清浄機 花粉・PM2.5対応", nameEn = "Air Purifier for Pollen & PM2.5",
            brandJa = "ピュアエア", brandEn = "PureAir",
            descriptionJa = "花粉やPM2.5を効果的に除去する空気清浄機です。静音設計で寝室でも快適に使用できます。",
            descriptionEn = "An air purifier that effectively removes pollen and PM2.5 particles. Its quiet design makes it comfortable to use even in the bedroom.",
            priceYen = 22000, categoryId = "home",
            imageUrls = images("home_5", 3), rating = 4.5, reviewCount = 430,
            tags = listOf(ProductTag.PRIME),
        ),

        // ===== beauty =====
        Product(
            id = "beauty_1",
            nameJa = "ビタミンC美容液", nameEn = "Vitamin C Serum",
            brandJa = "グローラボ", brandEn = "GlowLab",
            descriptionJa = "高濃度ビタミンCを配合した美容液です。毎日のスキンケアに取り入れることで明るい肌印象へ導きます。",
            descriptionEn = "A serum formulated with a high concentration of vitamin C. Daily use helps support a brighter, more radiant-looking complexion.",
            priceYen = 2980, categoryId = "beauty",
            imageUrls = images("beauty_1", 4), rating = 4.4, reviewCount = 1500,
            tags = listOf(ProductTag.BESTSELLER),
        ),
        Product(
            id = "beauty_2",
            nameJa = "速乾ヘアドライヤー", nameEn = "Quick-Dry Hair Dryer",
            brandJa = "エアロドライ", brandEn = "AiroDry",
            descriptionJa = "大風量でスピーディーに乾かせるヘアドライヤーです。マイナスイオン機能で髪をまとまりやすくします。",
            descriptionEn = "A hair dryer with powerful airflow for fast drying. Negative ion technology helps keep hair smooth and manageable.",
            priceYen = 8900, listPriceYen = 11000, categoryId = "beauty",
            imageUrls = images("beauty_2", 3), rating = 4.3, reviewCount = 670,
            tags = listOf(ProductTag.SALE),
        ),
        Product(
            id = "beauty_3",
            nameJa = "リップクリーム 3色セット", nameEn = "Lip Balm Set of 3",
            brandJa = "ピュアリップス", brandEn = "PureLips",
            descriptionJa = "うるおいを閉じ込める保湿成分配合のリップクリーム3本セットです。持ち運びに便利なミニサイズです。",
            descriptionEn = "A set of three moisturizing lip balms that lock in hydration. The mini size makes them easy to carry with you.",
            priceYen = 1200, categoryId = "beauty",
            imageUrls = images("beauty_3", 3), rating = 4.0, reviewCount = 88,
        ),
        Product(
            id = "beauty_4",
            nameJa = "洗顔ブラシ 電動タイプ", nameEn = "Electric Facial Cleansing Brush",
            brandJa = "クリアスキン", brandEn = "ClearSkin",
            descriptionJa = "毛穴の奥までやさしく洗い上げる電動洗顔ブラシです。防水設計でお風呂場でも安心して使用できます。",
            descriptionEn = "An electric cleansing brush that gently reaches deep into pores. Its waterproof design makes it safe to use in the shower.",
            priceYen = 4500, categoryId = "beauty",
            imageUrls = images("beauty_4", 3), rating = 3.9, reviewCount = 210,
            tags = listOf(ProductTag.NEW),
        ),

        // ===== books =====
        Product(
            id = "books_1",
            nameJa = "深夜の訪問者(ミステリー小説)", nameEn = "The Midnight Visitor (Mystery Novel)",
            brandJa = "ミステリープレス", brandEn = "Mystery Press",
            descriptionJa = "予測不能などんでん返しが話題のミステリー小説です。一度読み始めたら止まらないと評判です。",
            descriptionEn = "A mystery novel praised for its unpredictable twists. Readers say once they start, they can't put it down.",
            priceYen = 1500, categoryId = "books",
            imageUrls = images("books_1", 3), rating = 4.6, reviewCount = 320,
            tags = listOf(ProductTag.BESTSELLER),
        ),
        Product(
            id = "books_2",
            nameJa = "毎日の家庭料理レシピ集", nameEn = "Everyday Home Cooking Recipes",
            brandJa = "ホームキッチンブックス", brandEn = "Home Kitchen Books",
            descriptionJa = "初心者でも作りやすいレシピを100点収録した家庭料理の本です。写真付きの手順でわかりやすく解説しています。",
            descriptionEn = "A cookbook featuring 100 beginner-friendly recipes for home cooking. Step-by-step photos make every dish easy to follow.",
            priceYen = 2200, listPriceYen = 2600, categoryId = "books",
            imageUrls = images("books_2", 3), rating = 4.3, reviewCount = 145,
        ),
        Product(
            id = "books_3",
            nameJa = "実践 経営戦略入門", nameEn = "Practical Introduction to Business Strategy",
            brandJa = "ビズストラテジー出版", brandEn = "BizStrategy Publishing",
            descriptionJa = "実際の企業事例をもとに経営戦略の基礎を解説するビジネス書です。経営者からビジネスパーソンまで幅広く役立ちます。",
            descriptionEn = "A business book that explains the fundamentals of strategy using real company case studies. Useful for executives and business professionals alike.",
            priceYen = 1800, listPriceYen = 2200, categoryId = "books",
            imageUrls = images("books_3", 3), rating = 4.1, reviewCount = 92,
        ),
        Product(
            id = "books_4",
            nameJa = "おやすみ どうぶつたち(絵本)", nameEn = "Goodnight, Animals (Picture Book)",
            brandJa = "リトルリーダーズ", brandEn = "Little Readers",
            descriptionJa = "やさしい絵柄と言葉で綴られた寝る前の読み聞かせに最適な絵本です。親子の時間をより豊かにします。",
            descriptionEn = "A picture book with gentle illustrations and words, perfect for bedtime reading. It makes parent-child time even more special.",
            priceYen = 1100, categoryId = "books",
            imageUrls = images("books_4", 3), rating = 4.7, reviewCount = 410,
            tags = listOf(ProductTag.NEW),
        ),

        // ===== sports =====
        Product(
            id = "sports_1",
            nameJa = "ヨガマット 厚手6mm", nameEn = "Yoga Mat 6mm Thick",
            brandJa = "フレックスフィット", brandEn = "FlexFit",
            descriptionJa = "滑りにくい素材を使用した厚手6mmのヨガマットです。クッション性が高く関節への負担を軽減します。",
            descriptionEn = "A 6mm-thick yoga mat made from a non-slip material. Its extra cushioning helps reduce strain on your joints.",
            priceYen = 2900, categoryId = "sports",
            imageUrls = images("sports_1", 4), rating = 4.2, reviewCount = 560,
            tags = listOf(ProductTag.BESTSELLER),
        ),
        Product(
            id = "sports_2",
            nameJa = "ランニングシューズ 軽量クッション", nameEn = "Lightweight Cushioned Running Shoes",
            brandJa = "ロードランナー", brandEn = "RoadRunner",
            descriptionJa = "衝撃吸収性に優れたソールを採用したランニングシューズです。長距離のランニングでも足への負担を軽減します。",
            descriptionEn = "Running shoes featuring a shock-absorbing sole. They reduce stress on your feet even during long-distance runs.",
            priceYen = 11000, listPriceYen = 14000, categoryId = "sports",
            imageUrls = images("sports_2", 4), rating = 4.5, reviewCount = 890,
            tags = listOf(ProductTag.SALE, ProductTag.PRIME),
        ),
        Product(
            id = "sports_3",
            nameJa = "ダンベルセット 可変式 20kg", nameEn = "Adjustable Dumbbell Set 20kg",
            brandJa = "アイアンコア", brandEn = "IronCore",
            descriptionJa = "重量を自由に変更できる可変式ダンベルセットです。省スペースで自宅トレーニングに最適です。",
            descriptionEn = "An adjustable dumbbell set that lets you change the weight freely. Its compact footprint is ideal for home workouts.",
            priceYen = 9800, categoryId = "sports",
            imageUrls = images("sports_3", 3), rating = 4.4, reviewCount = 230,
            tags = listOf(ProductTag.LOW_STOCK),
        ),
        Product(
            id = "sports_4",
            nameJa = "2人用 軽量テント", nameEn = "2-Person Lightweight Tent",
            brandJa = "トレイルキャンプ", brandEn = "TrailCamp",
            descriptionJa = "設営が簡単な2人用の軽量テントです。防水性に優れ、突然の雨でも安心してキャンプを楽しめます。",
            descriptionEn = "A lightweight 2-person tent that's quick to set up. Excellent water resistance keeps you comfortable even in sudden rain.",
            priceYen = 18500, categoryId = "sports",
            imageUrls = images("sports_4", 3), rating = 4.3, reviewCount = 175,
        ),

        // ===== grocery =====
        Product(
            id = "grocery_1",
            nameJa = "高級煎茶 100g", nameEn = "Premium Sencha Green Tea 100g",
            brandJa = "ティーリーフ", brandEn = "TeaLeaf Co.",
            descriptionJa = "旨味豊かな一番茶を使用した高級煎茶です。丁寧に仕上げた茶葉が芳醇な香りを引き立てます。",
            descriptionEn = "A premium sencha green tea made from rich first-flush leaves. Carefully finished leaves bring out a fragrant, mellow aroma.",
            priceYen = 1200, categoryId = "grocery",
            imageUrls = images("grocery_1", 3), rating = 4.5, reviewCount = 340,
            tags = listOf(ProductTag.BESTSELLER),
        ),
        Product(
            id = "grocery_2",
            nameJa = "素焼きミックスナッツ 1kg", nameEn = "Roasted Mixed Nuts 1kg",
            brandJa = "ナッツハーベスト", brandEn = "NutHarvest",
            descriptionJa = "アーモンドやくるみなど4種の素焼きナッツをミックスしました。無塩・無油で毎日のおやつに安心して楽しめます。",
            descriptionEn = "A mix of four kinds of roasted nuts, including almonds and walnuts. Unsalted and oil-free, they make a healthy everyday snack.",
            priceYen = 1800, categoryId = "grocery",
            imageUrls = images("grocery_2", 3), rating = 4.2, reviewCount = 210,
        ),
        Product(
            id = "grocery_3",
            nameJa = "エキストラバージンオリーブオイル 500ml", nameEn = "Extra Virgin Olive Oil 500ml",
            brandJa = "オリーブゴールド", brandEn = "OliveGold",
            descriptionJa = "低温圧搾で仕上げたエキストラバージンオリーブオイルです。フルーティーな香りがサラダや料理を引き立てます。",
            descriptionEn = "A cold-pressed extra virgin olive oil. Its fruity aroma enhances salads and everyday cooking alike.",
            priceYen = 1500, listPriceYen = 1900, categoryId = "grocery",
            imageUrls = images("grocery_3", 3), rating = 4.4, reviewCount = 180,
            tags = listOf(ProductTag.SALE),
        ),
        Product(
            id = "grocery_4",
            nameJa = "醤油ラーメン 12食セット", nameEn = "Soy Sauce Ramen 12-Pack",
            brandJa = "ヌードルハウス", brandEn = "NoodleHouse",
            descriptionJa = "コクのある醤油スープが自慢のインスタントラーメン12食セットです。忙しい日の食事にも手軽に用意できます。",
            descriptionEn = "A 12-pack of instant ramen featuring a rich soy sauce broth. A quick and easy meal option for busy days.",
            priceYen = 1980, categoryId = "grocery",
            imageUrls = images("grocery_4", 3), rating = 3.8, reviewCount = 420,
        ),

        // ===== toys =====
        Product(
            id = "toys_1",
            nameJa = "ブロック知育セット 300ピース", nameEn = "Building Blocks Set 300 Pieces",
            brandJa = "ブロックジョイ", brandEn = "BlockJoy",
            descriptionJa = "創造力を育む300ピースのブロックセットです。カラフルなパーツで自由な発想遊びを楽しめます。",
            descriptionEn = "A 300-piece building block set that nurtures creativity. Colorful pieces encourage free, imaginative play.",
            priceYen = 6500, categoryId = "toys",
            imageUrls = images("toys_1", 4), rating = 4.6, reviewCount = 380,
            tags = listOf(ProductTag.BESTSELLER),
        ),
        Product(
            id = "toys_2",
            nameJa = "ラジコンカー オフロードタイプ", nameEn = "Off-Road Remote Control Car",
            brandJa = "スピーディーRC", brandEn = "SpeedyRC",
            descriptionJa = "凹凸のある地面もぐんぐん走れるオフロード仕様のラジコンカーです。充電式バッテリーで繰り返し遊べます。",
            descriptionEn = "An off-road remote control car that powers over bumpy terrain with ease. The rechargeable battery lets kids play again and again.",
            priceYen = 8900, listPriceYen = 11500, categoryId = "toys",
            imageUrls = images("toys_2", 4), rating = 4.3, reviewCount = 260,
            tags = listOf(ProductTag.SALE, ProductTag.NEW),
        ),
        Product(
            id = "toys_3",
            nameJa = "くまのぬいぐるみ Mサイズ", nameEn = "Teddy Bear Plush Medium",
            brandJa = "カドルフレンズ", brandEn = "CuddleFriends",
            descriptionJa = "ふわふわの手触りが心地よいクマのぬいぐるみです。優しい色合いでお子様への贈り物にも喜ばれます。",
            descriptionEn = "A teddy bear plush with a wonderfully soft texture. Its gentle coloring makes it a lovely gift for children.",
            priceYen = 2400, categoryId = "toys",
            imageUrls = images("toys_3", 3), rating = 4.7, reviewCount = 190,
        ),
        Product(
            id = "toys_4",
            nameJa = "ジグソーパズル 1000ピース 風景画", nameEn = "Jigsaw Puzzle 1000 Pieces Landscape",
            brandJa = "パズルマインド", brandEn = "PuzzleMind",
            descriptionJa = "美しい風景画をモチーフにした1000ピースのジグソーパズルです。集中して取り組む時間が心を落ち着かせます。",
            descriptionEn = "A 1000-piece jigsaw puzzle featuring a beautiful landscape scene. Focusing on the pieces offers a calming, mindful pastime.",
            priceYen = 1800, categoryId = "toys",
            imageUrls = images("toys_4", 3), rating = 4.1, reviewCount = 95,
        ),
    )

    val reviews: List<Review> = listOf(
        // electronics_1
        Review("rev_electronics_1_1", "electronics_1", "田中さくら", 5, "音質が素晴らしい", "Amazing sound quality",
            "ノイズキャンセリングの効きが良く、通勤中も快適に音楽を楽しめます。バッテリーも長持ちです。",
            "The noise cancellation works great and makes my commute much more pleasant. Battery life is excellent too.",
            "2026-05-12"),
        Review("rev_electronics_1_2", "electronics_1", "Kevin M.", 4, "コスパ良し", "Great value",
            "この価格でこの音質は満足です。ケースがもう少しコンパクトだと嬉しいです。",
            "Great sound for the price. Wish the charging case were a bit smaller, but overall very happy.",
            "2026-05-28"),
        Review("rev_electronics_1_3", "electronics_1", "佐藤健太", 5, "防水性能に驚き", "Impressed by water resistance",
            "ジム通いで汗をかいても問題なく使えています。装着感も軽くて疲れません。",
            "Holds up great even with sweat during workouts. Lightweight fit that doesn't tire my ears.",
            "2026-06-15"),
        // electronics_3
        Review("rev_electronics_3_1", "electronics_3", "Emily R.", 5, "打鍵感が最高", "Fantastic typing feel",
            "タクタイル感がしっかりしていて長時間のタイピングも快適です。バックライトも綺麗。",
            "The tactile feedback is excellent and typing for hours feels great. The backlight looks nice too.",
            "2026-06-02"),
        Review("rev_electronics_3_2", "electronics_3", "山本直樹", 4, "打鍵音がやや大きい", "A bit loud",
            "打鍵感は良いですが音が少し大きめです。静かな環境では気になるかもしれません。",
            "Typing feel is great but the click sound is a bit loud, might be noticeable in quiet rooms.",
            "2026-06-20"),
        // electronics_4
        Review("rev_electronics_4_1", "electronics_4", "鈴木愛", 4, "旅行に必須", "Travel essential",
            "軽くて持ち運びやすいのに大容量で助かります。旅行や出張には欠かせません。",
            "Lightweight and portable yet high capacity. Perfect for trips and business travel.",
            "2026-04-30"),
        Review("rev_electronics_4_2", "electronics_4", "David K.", 5, "充電速度が速い", "Charges fast",
            "急速充電に対応していてスマホがすぐに満タンになります。値段も手頃です。",
            "Fast charging support means my phone tops up quickly. Also very affordably priced.",
            "2026-05-18"),
        // electronics_5
        Review("rev_electronics_5_1", "electronics_5", "高橋美咲", 5, "留守中の掃除が楽に", "Cleans while I'm out",
            "外出中に自動で掃除してくれるのでとても助かっています。マッピングも正確です。",
            "It cleans automatically while I'm away, which is a huge help. Mapping is very accurate.",
            "2026-05-05"),
        Review("rev_electronics_5_2", "electronics_5", "Sophia L.", 4, "静音性が良い", "Runs quietly",
            "動作音が静かで夜間の稼働も気になりません。吸引力も十分です。",
            "Operates quietly enough to run at night without bothering anyone. Suction power is solid too.",
            "2026-05-22"),
        Review("rev_electronics_5_3", "electronics_5", "伊藤蓮", 5, "アプリ連携が便利", "Handy app integration",
            "アプリからスケジュール設定できるのが便利です。段差も問題なく乗り越えます。",
            "Being able to schedule cleanings from the app is very convenient. Handles small thresholds with no issue.",
            "2026-06-08"),
        // electronics_6
        Review("rev_electronics_6_1", "electronics_6", "Chris P.", 5, "軽くて持ち運びやすい", "Light and portable",
            "1kg未満とは思えないほど頑丈で、バッテリーも一日中持ちます。仕事用に最適です。",
            "Feels surprisingly sturdy for under 1kg, and the battery easily lasts all day. Great for work.",
            "2026-06-11"),
        Review("rev_electronics_6_2", "electronics_6", "Rachel T.", 4, "動作は快適だが価格が高め", "Smooth but pricey",
            "動作はサクサクで満足していますが、価格はやや高めに感じます。",
            "Performance is smooth and I'm satisfied, though the price feels a bit steep.",
            "2026-06-27"),
        // fashion_2
        Review("rev_fashion_2_1", "fashion_2", "Mia S.", 5, "着心地が最高", "Super comfortable",
            "生地が軽くて涼しく、夏のお出かけにぴったりです。柄も可愛くて気に入っています。",
            "The fabric is light and airy, perfect for summer outings. Love the cute floral pattern too.",
            "2026-05-09"),
        Review("rev_fashion_2_2", "fashion_2", "花子", 4, "サイズ感がやや大きめ", "Runs a bit large",
            "デザインは気に入っていますが、サイズはワンサイズ小さめを選んでも良いかもしれません。",
            "I love the design, though I'd suggest sizing down as it runs a bit large.",
            "2026-05-30"),
        // fashion_3
        Review("rev_fashion_3_1", "fashion_3", "James F.", 5, "履き心地抜群", "Extremely comfortable",
            "インソールのクッション性が高く、長時間歩いても疲れにくいです。見た目もシンプルで合わせやすい。",
            "The cushioned insole makes long walks much easier on my feet. Simple design that goes with everything.",
            "2026-05-14"),
        Review("rev_fashion_3_2", "fashion_3", "小林さやか", 5, "本革の質感が良い", "Great leather quality",
            "本革ならではの質感があり、履くほどに馴染んできます。長く愛用できそうです。",
            "The genuine leather has a great feel that improves with wear. I can tell this will last for years.",
            "2026-06-03"),
        Review("rev_fashion_3_3", "fashion_3", "Noah B.", 4, "コーディネートしやすい", "Easy to style",
            "どんな服にも合わせやすいデザインで重宝しています。サイズ選びは慎重にどうぞ。",
            "Versatile design that pairs with almost any outfit. Just be careful when choosing your size.",
            "2026-06-19"),
        // fashion_5
        Review("rev_fashion_5_1", "fashion_5", "渡辺ゆき", 5, "上品なデザイン", "Elegant design",
            "シンプルでどんな服装にも合う上品な腕時計です。プレゼントにも喜ばれました。",
            "A simple, elegant watch that matches any outfit. Also made a great gift.",
            "2026-05-25"),
        Review("rev_fashion_5_2", "fashion_5", "Daniel W.", 4, "バンドの調整が必要", "Band needed adjusting",
            "見た目は満点ですが、バンドのサイズ調整が必要でした。お店で調整してもらいました。",
            "Looks fantastic, though the band needed resizing. Had it adjusted at the store, no problem after that.",
            "2026-06-10"),
        // home_2
        Review("rev_home_2_1", "home_2", "Olivia H.", 5, "首の負担が減った", "Less neck strain",
            "朝起きたときの首の痛みが減りました。通気性も良く快適です。",
            "I wake up with much less neck pain now. Also stays breathable and comfortable through the night.",
            "2026-04-22"),
        Review("rev_home_2_2", "home_2", "中村大輔", 4, "少し硬めの感触", "A bit firm",
            "低反発ですが少し硬めに感じました。慣れれば快適に眠れます。",
            "It's memory foam but felt a bit firm to me at first. Comfortable once you get used to it.",
            "2026-05-17"),
        Review("rev_home_2_3", "home_2", "Ken T.", 5, "リピート購入しました", "Bought a second one",
            "使い心地が良くて家族用にもう一つ購入しました。カバーも洗濯しやすいです。",
            "Loved it so much I bought a second one for my family. The cover is also easy to wash.",
            "2026-06-05"),
        // home_4
        Review("rev_home_4_1", "home_4", "吉田真央", 5, "目に優しい", "Easy on the eyes",
            "明るさ調整の幅が広く、読書にも作業にもちょうど良い明るさに設定できます。",
            "The wide brightness range lets me set the perfect light for both reading and work.",
            "2026-06-01"),
        Review("rev_home_4_2", "home_4", "Yuki N.", 4, "デザインがシンプル", "Simple design",
            "デスクに置いても邪魔にならないコンパクトなサイズです。もう少し明るいと嬉しいです。",
            "Compact enough not to clutter the desk. Would appreciate a slightly brighter max setting.",
            "2026-06-24"),
        // home_5
        Review("rev_home_5_1", "home_5", "Aiko M.", 5, "花粉の季節に大活躍", "Great during pollen season",
            "花粉症がひどい季節でも部屋の空気がきれいに感じます。動作音も静かです。",
            "Even during peak pollen season, the air in my room feels noticeably cleaner. Runs quietly too.",
            "2026-04-18"),
        Review("rev_home_5_2", "home_5", "松本翔太", 4, "フィルター交換costがやや高い", "Filter cost is a bit high",
            "効果は実感していますが、交換フィルターの価格がやや高めなのが気になります。",
            "The effectiveness is real, though I wish the replacement filters were a bit cheaper.",
            "2026-05-31"),
        // beauty_1
        Review("rev_beauty_1_1", "beauty_1", "James F.", 5, "肌のトーンが明るくなった", "Brighter complexion",
            "使い始めて2週間ほどで肌のトーンが明るくなった気がします。伸びも良く使いやすいです。",
            "After about two weeks my skin looks noticeably brighter. Spreads easily and feels great to use.",
            "2026-04-25"),
        Review("rev_beauty_1_2", "beauty_1", "石井美穂", 4, "香りが少し独特", "Scent is a bit unique",
            "効果には満足していますが、香りが少し独特に感じる人もいるかもしれません。",
            "Very happy with the results, though the scent might be an acquired taste for some.",
            "2026-05-13"),
        Review("rev_beauty_1_3", "beauty_1", "Emily R.", 5, "毎日のケアに欠かせない", "A daily essential",
            "べたつかずさらっとした使用感で毎日のスキンケアに取り入れやすいです。",
            "Lightweight, non-sticky texture that's easy to work into a daily skincare routine.",
            "2026-06-07"),
        // beauty_2
        Review("rev_beauty_2_1", "beauty_2", "小川あゆみ", 5, "乾く時間が短縮", "Cuts drying time",
            "風量が強く乾かす時間がかなり短縮されました。髪もまとまりやすくなりました。",
            "The powerful airflow cuts my drying time significantly, and my hair stays smoother afterward.",
            "2026-05-02"),
        Review("rev_beauty_2_2", "beauty_2", "Kevin M.", 4, "やや重量がある", "A bit heavy",
            "パワーは十分ですが、長時間持つと少し腕が疲れます。",
            "Plenty of power, though it can tire your arm a bit during extended use.",
            "2026-05-26"),
        // books_1
        Review("rev_books_1_1", "books_1", "森田陽子", 5, "一気読みしました", "Read it in one sitting",
            "展開が読めず最後まで一気に読んでしまいました。伏線の回収が見事です。",
            "The plot kept me guessing and I finished it in one sitting. The foreshadowing pays off beautifully.",
            "2026-04-20"),
        Review("rev_books_1_2", "books_1", "Rachel T.", 5, "予想外の結末", "Unexpected ending",
            "まさかの結末に驚かされました。ミステリー好きにはたまらない一冊です。",
            "The ending completely surprised me. A must-read for any mystery fan.",
            "2026-05-11"),
        Review("rev_books_1_3", "books_1", "藤田健", 4, "文章が読みやすい", "Easy to read",
            "文章がテンポ良く読みやすいです。次作も楽しみにしています。",
            "Well-paced writing that's easy to follow. Looking forward to the next installment.",
            "2026-06-01"),
        // books_4
        Review("rev_books_4_1", "books_4", "岡田真理", 5, "寝かしつけに最適", "Perfect for bedtime",
            "優しい絵と言葉で子供がすぐに気に入りました。毎晩の読み聞かせが楽しみです。",
            "The gentle illustrations and words won my child over instantly. Bedtime reading is now a joy.",
            "2026-05-08"),
        Review("rev_books_4_2", "books_4", "Noah B.", 5, "プレゼントに最適", "Great gift",
            "友人の出産祝いに贈りました。とても喜んでもらえました。",
            "Gave this as a baby shower gift and it was very well received.",
            "2026-06-14"),
        // sports_1
        Review("rev_sports_1_1", "sports_1", "清水花", 4, "厚みがちょうど良い", "Just the right thickness",
            "膝への負担が減り、床の硬さが気にならなくなりました。持ち運び用のストラップも便利です。",
            "The extra thickness reduces stress on my knees and the hard floor is no longer an issue. The carry strap is handy too.",
            "2026-04-27"),
        Review("rev_sports_1_2", "sports_1", "David K.", 5, "滑りにくくて安心", "Great grip",
            "汗をかいても滑りにくく安心してポーズが取れます。色も豊富で選びやすいです。",
            "Doesn't slip even when I sweat, so I can hold poses with confidence. Nice color selection too.",
            "2026-05-19"),
        // sports_2
        Review("rev_sports_2_1", "sports_2", "Sophia L.", 5, "足への負担が少ない", "Easy on the feet",
            "クッション性が高く、長距離を走っても足が痛くなりません。フィット感も良好です。",
            "The cushioning is excellent and my feet don't hurt even after long runs. Fit is great too.",
            "2026-05-03"),
        Review("rev_sports_2_2", "sports_2", "村上健一", 4, "デザインが好み", "Love the design",
            "軽量で走りやすく、デザインもスタイリッシュで気に入っています。",
            "Lightweight and easy to run in, plus the stylish design is a nice bonus.",
            "2026-05-21"),
        Review("rev_sports_2_3", "sports_2", "Chris P.", 5, "サイズ展開が豊富", "Great size range",
            "サイズ展開が豊富で自分にぴったりの一足が見つかりました。耐久性も十分です。",
            "Wide size range made it easy to find the perfect fit. Durability has been solid as well.",
            "2026-06-16"),
        // grocery_1
        Review("rev_grocery_1_1", "grocery_1", "永井美咲", 5, "香りが豊か", "Rich aroma",
            "淹れたときの香りがとても良く、毎朝の楽しみになっています。",
            "The aroma when brewed is wonderful and has become a daily morning pleasure.",
            "2026-04-15"),
        Review("rev_grocery_1_2", "grocery_1", "Olivia H.", 4, "少し高価だが価値あり", "A bit pricey but worth it",
            "価格はやや高めですが、品質を考えると納得の価格です。",
            "It's on the pricier side, but the quality more than justifies the cost.",
            "2026-05-06"),
        // toys_1
        Review("rev_toys_1_1", "toys_1", "橋本さくら", 5, "子供が夢中に", "Kids love it",
            "子供が何時間も夢中で遊んでいます。パーツも丈夫で壊れにくいです。",
            "My kids play with it for hours without getting bored. The pieces are sturdy and hold up well.",
            "2026-04-29"),
        Review("rev_toys_1_2", "toys_1", "Mia S.", 5, "創造力が育つ", "Sparks creativity",
            "自由な発想で色々な形を作れて、想像力を育てるのに最適です。",
            "Kids can freely build all kinds of shapes, which is great for fostering creativity.",
            "2026-05-24"),
        Review("rev_toys_1_3", "toys_1", "本田拓也", 4, "収納ボックス付きが嬉しい", "Nice storage box included",
            "収納ボックスが付属していて片付けが楽です。ピースも紛失しにくいです。",
            "Comes with a storage box that makes cleanup easy and helps prevent losing pieces.",
            "2026-06-09"),
        // toys_2
        Review("rev_toys_2_1", "toys_2", "Daniel W.", 4, "バッテリーが長持ち", "Battery lasts a while",
            "充電式でランニングコストがかからず助かります。悪路走破性も高いです。",
            "Rechargeable battery keeps running costs down, which is great. Handles rough terrain well too.",
            "2026-05-16"),
        Review("rev_toys_2_2", "toys_2", "田村梨花", 5, "誕生日プレゼントに好評", "Great birthday gift",
            "息子の誕生日プレゼントに購入しましたが、とても喜んでいます。操作も簡単です。",
            "Bought this for my son's birthday and he absolutely loves it. Easy to control too.",
            "2026-06-22"),
    )
}
